### PR TITLE
Update all depencies to latest version just to keep it up to date!

### PR DESCRIPTION
**Pull request by Allov**

### CODE REVIEW

**Comment by belohlavek** [comment]
I'll look into this tomorrow, sorry for the delay :sweat_smile:

**Comment by Allov** [comment]
Phaser got updated yesterday, I updated it.

**Comment by belohlavek** [comment]
Sorry for the delay and thanks for the help :+1:

**Comment by belohlavek** [comment]
Sorry but I had to rollback. When I merged your pull request you had a commit 'remote tests' that wasn't relevant for this repository. Please fix that and submit a new pull request (should only be 2 commits), I'll be happy to merge it :smile:

**Comment by Allov** [comment]
In fact it's "**remove** tests". The code isn't there anymore.

**Comment by belohlavek** [comment]
Exactly, there's a commit removing something that was never there in the first place.

**Pull request merged**
