### PR TITLE
Fixed 'production' mode script to run in both windows and linux

### PR DESCRIPTION
**Pull request by spayton**
Made the 'production' mode script command compatible with both a windows and linux standard command line processors.

Tested in Win7Ult and Ubuntu 14.04

### CODE REVIEW

**Comment by belohlavek** [comment]
I can't get this change to run on Ubuntu 15.04. Any tips on how you got it to work?
In any case, I have in mind a couple of workarounds to make it 'cross-platform' if we fail to find an universal solution for setting NODE_ENV.

**Comment by spayton** [comment]
Hmmm, sounds like perhaps I screwed up and didn't test properly.  I'll test again

**Comment by spayton** [comment]
Ok, tried it again from scratch on a different Ubuntu installation and it works.  Here's my terminal session, you'll see all the versions of everything, a grep for the NODE_ENV to make sure its using the version I modded and finally the production run.

What happens when it fails for you?

term

**Comment by spayton** [comment]
Ah, the penny has dropped.  I was assuming it worked because it didn't complain, but it hasn't actually set NODE_ENV - so not working.

**Comment by belohlavek** [comment]
Yeah, sorry for not giving further details, my bad! :sweat_smile:
I'll probably use something like [yargs](https://github.com/bcoe/yargs) to fix it. Also, I'll open an issue just for tracking purposes.

Thanks for reporting the problem!

**Pull request closed without merging**
